function(get_no_sufix_dir OUTPUT_VAR target_path)
    get_filename_component(file_name ${target_path} NAME)
    if(file_name MATCHES "")
        return()
    endif()
    string(REGEX REPLACE "${file_name}" "" no_sufix_file_dir "${target_path}")
    set(var "")
    if(no_sufix_file_dir MATCHES ${CMAKE_CURRENT_SOURCE_DIR})
        string(REGEX REPLACE "${CMAKE_CURRENT_SOURCE_DIR}" "" var "${no_sufix_file_dir}")
    elseif(no_sufix_file_dir MATCHES ${CMAKE_CURRENT_BINARY_DIR})
        string(REGEX REPLACE "${CMAKE_CURRENT_BINARY_DIR}\include" "" var "${no_sufix_file_dir}")
    endif()
    set(${OUTPUT_VAR} ${var} PARENT_SCOPE)
    # message("target file " ${target_path} "   " ${OUTPUT_VAR})
endfunction()

function(find_depends_src OUTPUT_VAR TARGET_DIR)
    set(fileList "")
    foreach(child ${TARGET_DIR})
        get_no_sufix_dir(file_dir ${child})
        if(NOT ${file_dir} MATCHES "build")
            LIST(APPEND fileList ${child})
            message("append value " ${file_dir})
        endif()
    endforeach()
    set(${OUTPUT_VAR} ${fileList} PARENT_SCOPE)
endfunction()

find_depends_src(SRC "${CMAKE_CURRENT_SOURCE_DIR}/include/")
